name: "Increment Version"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Increment patch version"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2.3.4

      - name: "Setup environment"
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          sudo python3 -m pip install bumpversion

      - name: "Bump version number"
        run: |
          if ! echo "$COMMIT_MSG" | grep 'New release'; then
            git config --local user.email "hello@qmk.fm"
            git config --local user.name "QMK Bot"
            bumpversion patch
          fi
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          tags: true

      - name: Trigger Release Action
        run: ./trigger_action
        env:
          QMK_BOT_TOKEN: ${{ secrets.QMK_BOT_TOKEN }}
